services:
  - docker

matrix:
  include:

    # python app
    - language: python
      python:
        - "3.8"

      before_install:
        - cd python-app

      install:
        - pip3 install -r requirements.txt

      script:
        - docker build -t $DOCKER_USER/python-app:latest python-app/
        - docker images

      after_success:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - docker push $DOCKER_USER/python-app:latest

      deploy:
        provider: pypi
        username:
        password:
          secure:
    
    # node app
    - language: node_js

      before_install:
        - cd node-app
      
      install:
        - npm install
      
      script:
        - docker build -t $DOCKER_USER/node-app:latest python-app/
        - docker images

      after_success:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - docker push $DOCKER_USER/python-app:latest

      deploy:
        provider: npm
        email:
        api_key:
      
    
