services:
- docker

matrix:
  include:

  - language: python
    python:
    - "3.8"
    env:
    - DOCKER_USER=sabattle
    - secure: "CR2GLBYdDw+VJ5YvRCO5Wq39iBrixNaQjaz1dYyJrJPVoDr+rnFtAbYmndFmArwGiaMQgo9uMs0v/GJ6qxL0wKDiveQ9ysRXVCciudH9awPuWp5ApoKDGPObpMBRcsYP+mp+EDl2UyLoiSsU8CrAFfeXVP0lPlwv7msWnAbQGDILxW7wkgDoUFw2mRgDfuUNJ+kNKRe33HmFu6w0n1sFTQmf7t5MntMrnFLzEdiCOppk97EfAc8/9oOZqAjzNP8CduKMSX+rwnfWWlwUUnM0hxy+n0e/YzHGbu3nhzWEoQxW+YjQVaH08/mKzkybQdPSp5PLalWuCFB38kITN+vsgLZjJyxNjfGSJEqp+wF+6TsJAthH+2WppQ2ke5OukpwdH6obCoc+lJ5C5pz4eueW3U0G8x58IgNxqOKLVikUfVgc+5PzWlrXka8M9u2jQpdsXcySvPuYjJcYT5RuMDijTYN4nGqtoUrNrZV2H5kA8stwsoKLHScxZg0/+8YV39WQmT6D+Ic1cvKPDQOwGMbk8GEStYVwzPeUSDmOJ7eA2RN5l4kqA/pJkLd7+RVu5IjwI8HE0otLgeQbY71cuCEJWauEmPCVnXBtsofpHkzQrqLSf0FR7qOFCKX4rlrC4xiN/1fBUtXbYmq+/UEPYkd/7JJx2rEmJKSRqkEbWGZpeUI="

    before_install:
    - cd python-app

    install:
    - pip3 install -r python-app/requirements.txt

    script:
    - docker build -t $DOCKER_USER/python-app:latest python-app/
    - docker images

    after_success:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
    - docker push $DOCKER_USER/python-app:latest

    deploy:
      provider: pypi
      username: "__token__"
      password:
        secure: "TxhqBlzUvybi2x2WOCBNlztPtLfw/D4/vXzyCcJFd5Cg6NuCMeQX+t+3U1tg/k2UVNxr4S3Fgo81VqMr9Ge08iONa8LN1Wj1pQb7m6nGRpt7Li3X+4DxYeDU3hjRTOBav2Iyzs1MwQcbAP169qn+on+8Y+uhX7/yjMfNLTKtMbf9JM4t+kIOmLWM5oXXAOetvDpUJ1Duf2U+ysd+8jdW9CROq8xw8jQFbP1hOFMMuNz/FXb18Y+wHotGIBCea/Xeu6uAJN0WUIxDnv5jG2GuobR+FcEr0/R0TwfOCgDknEcwBQzhhmh5Svp0k2zWpqx2hGj0c4ohKvsdxbLForX0SppWGkcO/8zCQ3bQh1G4yWL+0REqCXjMcTvHN201llVNmJvGE8cn/EoZLPLwBVhkVgKTwg+ilphbDjVAwN3spKCqOxX6rQySoMsYbVBSjsiahDNJ5Ng7NryR9grI/BcjXtfuEgzXWEUoquVFG2+k9cydjBNyMea9CfsVm7UVduT4+qN7h9sKbPCN9dvITNTmf75CFpS4BboYYZ5nFCMq4yiTJEzwJdnmbAq8PN/uHNMmSjFZZR0Qx4ZxtkT+oOJwYAoBpf3AYN75eihq5YxFPdyxr1ePoyOgbFEVozrdkSPJ1lNJys8MNdN991J5D21A7zKj0YwevL3AOxr+8vkcqxA="
      on:
        all_branches: true
      skip_existing: true

  - language: node_js
    env:
    - DOCKER_USER=sabattle
    - secure: "emr0hzS7lb8FPcp5SQdtkl3X7LHWS75eCpgbjWfoGvnSfzb5BFMvg3+3bFaD4SlCUlmAavSoOyamixieEXIc5I+w5hM8t7AbXjFkgqysvSyNiVhWkk3EhUqyfdlYFXXym0B3uEuj0iAoV1KZQTeNbGzLmPpkxu9abD44l/NyGev1jkamnXK+p685DJ/EZPyAoNRMorqDFuXsBos2Npo0wQkDBbdu5w7OjZXXbDdGI6xINnHzUZhlcbKvT4gH9paW0TrbImd8EQXikFWb1lm9541ZFjf2w7+ZS9o0ZDBIBVCZp2Xg3CWwdY2iFjygeTLl9NQ9d8JaNB+GShw4bHclzTkvwM3aJ6L5QvepJ/ODXN6xJf15MK1/si5W3vhzxL92JvssruEw0ljurMp6iaH68gve/olX4ZACeTKVSwp95TFP3IKJQWtdB8LCPyc+85Uq32ELqfgkeUKXxsi/LnVfTHBJsgZothRgBCVPJ1eIosTosbzpygpCLQgnb4UNisxeeUk0cQdokXIXF3lkdCqnL+dhtgJOw7aw5IPPddp6PiGsKxcrZNIBkPUIZAeDaxnJokIAHUshh9gz2VTrYZm7+z9pglh+EdtZSeVPusbXijsoHNQXjt6c1X0KyHvavoYd9/2+FdVVQHiwy/zmQ3c16nqXm4PpwZGA1YJFibeeMAc="

    before_install:
    - cd node-app

    install:
    - npm install

    script:
    - docker build -t $DOCKER_USER/node-app:latest .
    - docker images

    after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push $DOCKER_USER/node-app:latest

    deploy:
      provider: npm
      email: sabattle@eckerd.edu
      api_key:
        secure: "R1iy8iB0fnf/I8LraDix23EBj6h9dPmgKZwkKqHR/g7M7eAvzwbXg8cOsdXBttHS45HjEw/BP/XkSwjGGYhtabD+/kVyq/YmfGnCguNXZGWauoQhgGnBJtZ5asqNGzUsNYk9i4RvBaYyhTIhSCqXBStyicZvEOoSluJNaoCEk40wyyGPchNrdCfu488nEUyfnbJZZ3OiPzucfjkwpBqy/tTQJEWxJ4GkZr7yDN1Z2QDQg7UnQokMgs4GPd+q25s0Y0T69yolEJtxb/BmHfuUtMluVH54/DelhuaP6fzEm/xdHr8pvw2o2AuKcpeXYQ01+3872bplcyvcxsXwS48YtlFZnPSP17wEk4fD84DiBnwfASd2TucC2rduiBrEudr6Gt/ESIReoVSvACwWGJU+xhMxeRGw/c1eWOA5PZIK+66c+gX5XYpM2UtqJMEUafOJhqIidQErnzPGEK+HJR82/RUBz7mEiJ/r3WV6VlTHgr1gJzctLmG3/uX45z3RdDMpIkXsPNcLSXUUfacYuVkC90mkQdpwNlJvc1VS486Rb2zbYOjr5kmymHvZdjdUYMbSv4tbtCV6D6sWxpykKgLW+q3yncBPV+6SaRv4r2KcN8DZb7KVyhu6v1Q0PG1BemsS2t4QsqdYMqDjMIiQ4Sjawlf0b4VfolW8ipEkyzfmAX0="
      on:
        all_branches: true
