apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: k8s-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005  
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: k8s-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30008  
  type: NodePort